import sys
import os
import json
import subprocess
import tempfile
try:
    import cv2
    import numpy as np
    from PIL import Image
    HAS_OPENCV = True
except ImportError:
    HAS_OPENCV = False

def process_potrace_vectorization(input_path, output_path, options):
    if not HAS_OPENCV:
        raise Exception("OpenCV and Pillow are required. Please install opencv-python and Pillow.")

    # 1. Read Image with OpenCV
    img = cv2.imread(input_path, cv2.IMREAD_UNCHANGED)
    if img is None:
        raise Exception("Could not read input image")

    height, width = img.shape[:2]
    
    # Handle alpha channel
    if img.shape[2] == 4:
        b, g, r, a = cv2.split(img)
        # Smart Alpha Cutoff: alpha < 128 becomes transparent
        _, alpha_mask = cv2.threshold(a, 128, 255, cv2.THRESH_BINARY)
        rgb = cv2.merge([b, g, r])
    else:
        alpha_mask = np.ones((height, width), dtype=np.uint8) * 255
        rgb = img

    # 2. Options
    noise_filter = options.get('noiseFilter', 2)
    min_shape_size = options.get('minShapeSize', 50)
    color_count = max(4, min(64, options.get('colorCount', 16)))
    scale = options.get('scale', 2)

    # 3. Upscale if scale > 1
    if scale > 1:
        rgb = cv2.resize(rgb, (width * scale, height * scale), interpolation=cv2.INTER_CUBIC)
        alpha_mask = cv2.resize(alpha_mask, (width * scale, height * scale), interpolation=cv2.INTER_NEAREST)

    # 4. Pre-processing: Gaussian Blur
    if noise_filter > 0:
        ksize = (noise_filter * 2 + 1, noise_filter * 2 + 1)
        rgb = cv2.GaussianBlur(rgb, ksize, 0)

    # 5. Color Quantization via K-Means
    pixels = rgb.reshape((-1, 3)).astype(np.float32)
    criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 20, 1.0)
    _, labels, centers = cv2.kmeans(pixels, color_count, None, criteria, 10, cv2.KMEANS_RANDOM_CENTERS)
    
    centers = np.uint8(centers)
    quantized = centers[labels.flatten()].reshape(rgb.shape)

    # 6. Generate SVG using Potrace CLI if available, or OpenCV Contour Bézier fallback
    potrace_available = False
    try:
        res = subprocess.run(["potrace", "--version"], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        if res.returncode == 0:
            potrace_available = True
    except FileNotFoundError:
        potrace_available = False

    svg_paths = []
    
    if potrace_available:
        # Potrace Server Flow
        unique_colors = np.unique(centers, axis=0)
        for color in unique_colors:
            # Mask for specific color
            mask = cv2.inRange(quantized, color, color)
            mask = cv2.bitwise_and(mask, alpha_mask)

            # Save BMP for potrace
            with tempfile.NamedTemporaryFile(suffix='.bmp', delete=False) as tmp_bmp, \
                 tempfile.NamedTemporaryFile(suffix='.svg', delete=False) as tmp_svg:

                cv2.imwrite(tmp_bmp.name, mask)
                tmp_bmp_path = tmp_bmp.name
                tmp_svg_path = tmp_svg.name

            try:
                cmd = [
                    "potrace",
                    "--svg",
                    "--alphamax", "1.2",
                    "--turdsize", str(min_shape_size),
                    "--output", tmp_svg_path,
                    tmp_bmp_path
                ]
                subprocess.run(cmd, check=True)

                with open(tmp_svg_path, 'r', encoding='utf-8') as f:
                    svg_data = f.read()

                # Extract path d content and format color
                hex_color = "#{:02x}{:02x}{:02x}".format(color[2], color[1], color[0])
                svg_paths.append(f'<g fill="{hex_color}">\n{svg_data}\n</g>')
            finally:
                if os.path.exists(tmp_bmp_path): os.remove(tmp_bmp_path)
                if os.path.exists(tmp_svg_path): os.remove(tmp_svg_path)

        final_svg = f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {width} {height}" width="{width}" height="{height}">\n'
        final_svg += '<!-- Generated by VXEL Server Potrace Engine -->\n'
        final_svg += '\n'.join(svg_paths)
        final_svg += '\n</svg>'

    else:
        # High Quality OpenCV Contour Vectorization Fallback
        unique_colors = np.unique(centers, axis=0)
        final_svg = f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {width} {height}" width="{width}" height="{height}">\n'
        final_svg += '<!-- Generated by VXEL OpenCV Vector Engine -->\n'

        for color in unique_colors:
            mask = cv2.inRange(quantized, color, color)
            mask = cv2.bitwise_and(mask, alpha_mask)

            contours, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_TC89_KCOS)
            hex_color = "#{:02x}{:02x}{:02x}".format(color[2], color[1], color[0])

            d_paths = []
            for cnt in contours:
                area = cv2.contourArea(cnt)
                if area >= min_shape_size:
                    epsilon = 0.005 * cv2.arcLength(cnt, True)
                    approx = cv2.approxPolyDP(cnt, epsilon, True)
                    
                    if len(approx) > 2:
                        pts = approx.reshape(-1, 2)
                        d = f"M {pts[0][0]/scale} {pts[0][1]/scale} "
                        for pt in pts[1:]:
                            d += f"L {pt[0]/scale} {pt[1]/scale} "
                        d += "Z"
                        d_paths.append(d)

            if d_paths:
                merged_d = " ".join(d_paths)
                final_svg += f'  <path d="{merged_d}" fill="{hex_color}" />\n'

        final_svg += '</svg>'

    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(final_svg)

if __name__ == '__main__':
    if len(sys.argv) < 3:
        print("Usage: python potrace_processor.py <input_img> <output_svg> [options_json]")
        sys.exit(1)

    input_img = sys.argv[1]
    output_svg = sys.argv[2]
    options_arg = json.loads(sys.argv[3]) if len(sys.argv) > 3 else {}

    process_potrace_vectorization(input_img, output_svg, options_arg)
